version: "2"

services:
  orders-aws:
    build:
      context: ./target/docker/orders-aws
    image: weaveworksdemos/orders-aws
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
      - ZIPKIN=zipkin
    ports:
      - "8082:80"
  orders-db:
    image: dwmkerr/dynamodb
    hostname: orders-db
    restart: always
    environment:
      - reschedule=on-node-failure
    ports:
      - "8080:8000"
